# Generated by Django 4.0.3 on 2022-03-24 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid1, editable='False', primary_key='True', serialize=False, verbose_name='PK')),
                ('nome', models.CharField(max_length=100, verbose_name='nome_completo')),
                ('idade', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='idade')),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorsiado(a)', 'Divorsiado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=14, verbose_name='estado_civil')),
                ('endereco', models.CharField(help_text='Bairro, Cidade - UF', max_length=100, verbose_name='endereco')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='telefone')),
                ('linkedin', models.URLField(max_length=150, verbose_name='linkedin')),
                ('objetivo', models.TextField(max_length=200)),
                ('formacao_academica', models.TextField(max_length=200)),
                ('idiomas', models.CharField(max_length=100, verbose_name='idioma')),
                ('outras_qualificacoes', models.TextField(max_length=200, verbose_name='Qualificações')),
                ('experiencia1', models.TextField(max_length=200, verbose_name='exp1')),
                ('experiencia2', models.TextField(max_length=200, verbose_name='exp2')),
                ('experiencia3', models.TextField(max_length=200, verbose_name='exp3')),
            ],
        ),
    ]
