# Generated by Django 4.0.3 on 2022-03-26 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid1, editable='False', primary_key='True', serialize=False, verbose_name='PK')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('idade', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Idade')),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorsiado(a)', 'Divorsiado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=14, verbose_name='Estado Civil')),
                ('endereco', models.CharField(help_text='Ex:  Bairro, Cidade - UF', max_length=100, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='Ex:  (24) 9983-6570', max_length=15, null=True, verbose_name='Telefone ou Celular')),
                ('linkedin', models.URLField(help_text='Ex:  https://linkedin.com/ronaldocerqueira', max_length=150, verbose_name='LinkedIn')),
                ('objetivo', models.CharField(max_length=200)),
                ('formacao_academica', models.TextField(max_length=400, verbose_name='Formação Acadêmica')),
                ('idiomas', models.CharField(blank='True', help_text='Ex:  Inglês Básico', max_length=100, verbose_name='Idioma')),
                ('outras_qualificacoes', models.TextField(max_length=800, verbose_name='Qualificações Profissionais')),
                ('empresa1', models.CharField(blank='True', help_text='Ex:  Contabilidade União - 03/2018 a 02/2022', max_length=100, verbose_name='Nome da Empresa e tempo de permanência')),
                ('experiencia1', models.TextField(blank='True', max_length=800, verbose_name='Atividades desempenhadas')),
                ('empresa2', models.CharField(blank='True', help_text='Ex:  Laboratórios Lux - 01/2011 a 08/2016', max_length=100, verbose_name='Nome da Empresa e tempo de permanência')),
                ('experiencia2', models.TextField(blank='True', max_length=800, verbose_name='Atividades desempenhadas')),
                ('empresa3', models.CharField(blank='True', help_text='Ex:  Mecânica Teixeira - 05/2009 a 06/2010', max_length=100, verbose_name='Nome da Empresa e tempo de permanência')),
                ('experiencia3', models.TextField(blank='True', max_length=800, verbose_name='Atividades desempenhadas ')),
            ],
        ),
    ]
