# Generated by Django 4.0.3 on 2022-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco',
            field=models.CharField(help_text='Ex:  Bairro, Cidade - UF', max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorsiado(a)', 'Divorsiado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=14, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia1',
            field=models.TextField(max_length=500, verbose_name='Experiência Profissional 1'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia2',
            field=models.TextField(max_length=500, verbose_name='Experiência Profissional 2'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia3',
            field=models.TextField(max_length=500, verbose_name='Experiência Profissional 3'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='formacao_academica',
            field=models.TextField(max_length=350, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='idade',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='idiomas',
            field=models.CharField(max_length=100, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='linkedin',
            field=models.URLField(max_length=150, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='outras_qualificacoes',
            field=models.TextField(max_length=500, verbose_name='Qualificações'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
