# Generated by Django 4.0.3 on 2022-03-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_candidato_email_alter_candidato_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='experiencia1',
            field=models.TextField(max_length=800, verbose_name='Experiência Profissional 1'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia2',
            field=models.TextField(max_length=800, verbose_name='Experiência Profissional 2'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia3',
            field=models.TextField(max_length=800, verbose_name='Experiência Profissional 3'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='formacao_academica',
            field=models.TextField(max_length=400, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='objetivo',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='outras_qualificacoes',
            field=models.TextField(max_length=800, verbose_name='Qualificações'),
        ),
    ]
